from typing import Any, Dict, NamedTuple

import gettext
_ = gettext.gettext


class Preset(NamedTuple):
    id: str
    job: str
    description: str
    options: Dict[str, Any]
    alt: int


presets = [
    Preset(
        id="hero",
        job=_("히어로"),
        description=_("두손도끼, 소오버 고정"),
        options={},
        alt=0,
    ),
    Preset(
        id="paladin",
        job=_("팔라딘"),
        description=_("두손둔기, 블레싱 아머 미발동"),
        options={},
        alt=0,
    ),
    Preset(
        id="darknight",
        job=_("다크나이트"),
        description=_("다크 스피어 10히트, 체력 100%, 리인카 쿨마다 사용"),
        options={},
        alt=0,
    ),
    Preset(
        id="archmage_fp",
        job=_("아크메이지불/독"),
        description=_("포이즌 노바 4히트, 언스 사용"),
        options={},
        alt=0,
    ),
    Preset(
        id="archmage_il",
        job=_("아크메이지썬/콜"),
        description=_("썬브 2히트, 언스 사용"),
        options={"thunder_break_hit": 2},
        alt=0,
    ),
    Preset(
        id="bishop",
        job=_("비숍"),
        description=_("피스메이커 3히트, 솔플, 언스 사용"),
        options={},
        alt=0,
    ),
    Preset(
        id="bowmaster",
        job=_("보우마스터"),
        description=_("애로우 레인 1줄기"),
        options={},
        alt=0,
    ),
    Preset(
        id="marksman",
        job=_("신궁"),
        description=_("거리 400"),
        options={"distance": 400},
        alt=0,
    ),
    Preset(
        id="marksman_distance_100",
        job=_("신궁"),
        description=_("거리 100"),
        options={"distance": 100},
        alt=1,
    ),
    Preset(
        id="pathfinder",
        job=_("패스파인더"),
        description=_("블래 210ms 디차 240ms"),
        options={},
        alt=0,
    ),
    Preset(
        id="nightlord",
        job=_("나이트로드"),
        description=_("스프 풀히트"),
        options={},
        alt=0,
    ),
    Preset(
        id="nightlord_spread_loss_1",
        job=_("나이트로드"),
        description=_("스프 1줄샘"),
        options={"spread_loss": 1},
        alt=1,
    ),
    Preset(
        id="shadower",
        job=_("섀도어"),
        description=_("KP3 1타 94.6% / 2타 100%"),
        options={},
        alt=0,
    ),
    Preset(
        id="dualblade",
        job=_("듀얼블레이드"),
        description=_("블토 태풍 5히트"),
        options={},
        alt=0,
    ),
    Preset(
        id="buccaneer",
        job=_("바이퍼"),
        description=_("카운터 어택 미발동"),
        options={},
        alt=0,
    ),
    Preset(
        id="corsair",
        job=_("캡틴"),
        description=_("데드아이 풀조준, 카운터 어택 미발동"),
        options={},
        alt=0,
    ),
    Preset(
        id="cannoneer",
        job=_("캐논슈터"),
        description=_("코코볼 27히트"),
        options={},
        alt=0,
    ),
    Preset(
        id="dawnwarrior",
        job=_("소울마스터"),
        description="",
        options={},
        alt=0,
    ),
    Preset(
        id="mihile",
        job=_("미하일"),
        description=_("솔플, 로얄가드 쿨마다"),
        options={},
        alt=0,
    ),
    Preset(
        id="mihile_royal_guard_false",
        job=_("미하일"),
        description=_("솔플, 로얄가드 안씀"),
        options={"royal_guard": False},
        alt=1,
    ),
    Preset(
        id="blazewizard",
        job=_("플레임위자드"),
        description=_("블비탈 4히트, 오비탈 분당 1350타"),
        options={"orbital_per_min": 1350},
        alt=0,
    ),
    Preset(
        id="blazewizard_orbital_1150",
        job=_("플레임위자드"),
        description=_("블비탈 4히트, 오비탈 분당 1150타"),
        options={"orbital_per_min": 1150},
        alt=1,
    ),
    Preset(
        id="windarcher",
        job=_("윈드브레이커"),
        description=_("하울링게일 58히트, 볼텍스 스피어 17히트"),
        options={},
        alt=0,
    ),
    Preset(
        id="nightwalker",
        job=_("나이트워커"),
        description=_("점샷 400ms"),
        options={"jump_rate": 1},
        alt=0,
    ),
    Preset(
        id="nightwalker_jump_0",
        job=_("나이트워커"),
        description=_("노점샷"),
        options={"jump_rate": 0},
        alt=1,
    ),
    Preset(
        id="thunderbreaker",
        job=_("스트라이커"),
        description=_("파섬"),
        options={"dealcycle": "waterwave"},
        alt=0,
    ),
    Preset(
        id="thunderbreaker_thunder",
        job=_("스트라이커"),
        description=_("벽섬"),
        options={"dealcycle": "thunder"},
        alt=1,
    ),
    Preset(
        id="blaster",
        job=_("블래스터"),
        description=_("매그팡 510ms"),
        options={},
        alt=0,
    ),
    Preset(
        id="demonslayer",
        job=_("데몬슬레이어"),
        description=_("블블 100%"),
        options={},
        alt=0,
    ),
    Preset(
        id="battlemage",
        job=_("배틀메이지"),
        description=_("좌우텔 분당 83회, 디버프 오라만, 명계문 미사용"),
        options={},
        alt=0,
    ),
    Preset(
        id="wildhunter",
        job=_("와일드헌터"),
        description=_("재규어 스톰 3히트"),
        options={},
        alt=0,
    ),
    Preset(
        id="mechanic",
        job=_("메카닉"),
        description="",
        options={},
        alt=0,
    ),
    Preset(
        id="xenon",
        job=_("제논"),
        description=_("오버로드 70초, 융합 680타"),
        options={},
        alt=0,
    ),
    Preset(
        id="aran",
        job=_("아란"),
        description="",
        options={},
        alt=0,
    ),
    Preset(
        id="evan",
        job=_("에반"),
        description=_("다오어 3히트, 다오어-브레스-브오어"),
        options={},
        alt=0,
    ),
    Preset(
        id="luminous",
        job=_("루미너스"),
        description="",
        options={},
        alt=0,
    ),
    Preset(
        id="mercedes",
        job=_("메르세데스"),
        description=_("엘고때 연계사이클"),
        options={"dealcycle": "combo"},
        alt=0,
    ),
    Preset(
        id="mercedes_ishtar",
        job=_("메르세데스"),
        description=_("엘고때 이슈타르"),
        options={"dealcycle": "ishtar"},
        alt=1,
    ),
    Preset(
        id="phantom_pathfinder",
        job=_("팬텀"),
        description=_("블디, 블디/크오체/파컷/불스아이, 체력 100%"),
        options={"dealcycle": "blast_discharge"},
        alt=0,
    ),
    Preset(
        id="phantom",
        job=_("팬텀"),
        description=_("얼드, 분노/크오체/파컷/불스아이, 체력 100%"),
        options={"dealcycle": "ultimate_drive"},
        alt=1,
    ),
    Preset(
        id="shade",
        job=_("은월"),
        description=_("분혼 격참 이동형 보스 판정, 약점 간파 적용"),
        options={"hp_rate": True},
        alt=0,
    ),
    Preset(
        id="shade_weakness_off",
        job=_("은월"),
        description=_("분혼 격참 이동형 보스 판정, 약점 간파 미적용"),
        options={"hp_rate": False},
        alt=1,
    ),
    Preset(
        id="kaiser",
        job=_("카이저"),
        description="",
        options={},
        alt=0,
    ),
    Preset(
        id="kain",
        job=_("카인"),
        description="",
        options={},
        alt=0,
    ),
    Preset(
        id="cadena",
        job=_("카데나"),
        description=_("1타캔슬 150ms, 캔슬 180ms, 윙대거 3틱"),
        options={},
        alt=0,
    ),
    Preset(
        id="angelicbuster",
        job=_("엔젤릭버스터"),
        description=_("스포트라이트 3중첩, 어피니티IV 가동률 94.18%"),
        options={"spotlight": 3},
        alt=0,
    ),
    Preset(
        id="angelicbuster_spotlight_2",
        job=_("엔젤릭버스터"),
        description=_("스포트라이트 2중첩, 어피니티IV 가동률 94.18%"),
        options={"spotlight": 2},
        alt=1,
    ),
    Preset(
        id="adele",
        job=_("아델"),
        description=_("게더링 80% 히트, 레조넌스 10초마다"),
        options={},
        alt=0,
    ),
    Preset(
        id="illium",
        job=_("일리움"),
        description="",
        options={},
        alt=0,
    ),
    Preset(
        id="ark",
        job=_("아크"),
        description=_("플레인 캔슬 270ms, 흉몽 캔슬 210ms"),
        options={},
        alt=0,
    ),
    Preset(
        id="hoyoung",
        job=_("호영"),
        description=_("금고봉/지진쇄/토파류"),
        options={},
        alt=0,
    ),
    Preset(
        id="zero",
        job=_("제로"),
        description=_("문피쉐, 카벨뚝"),
        options={"dealcycle": "alpha_new"},
        alt=0,
    ),
    Preset(
        id="zero_alpha_legacy",
        job=_("제로"),
        description=_("어파스, 카벨뚝"),
        options={"dealcycle": "alpha_legacy"},
        alt=1,
    ),
    Preset(
        id="kinesis",
        job=_("키네시스"),
        description=_("메테리얼"),
        options={"dealcycle": "material"},
        alt=0,
    ),
    Preset(
        id="kinesis_shot",
        job=_("키네시스"),
        description=_("샷 80%"),
        options={"dealcycle": "shot", "shot_rate": 0.8},
        alt=1,
    ),
]

preset_dict = {el.id: el for el in presets}


def get_preset(id: str):
    return preset_dict[id]


def get_preset_list():
    return presets
